name: Build and publish PyJet to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Позволяет запускать воркфлоу вручную из вкладки Actions!

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.0
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp311-*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibuildwheel-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Публикуем на PyPI только если это был запуск по тегу v*
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibuildwheel-wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
